### ISSUE TITLE
能否增加目录绕过字典 

### ISSUE THREAD

**Issue by weujieytt** [API-Security/APIKit#14]
例如：
/;/actuator/env
//actuator/..;/env

**Comment by yuligesec** [comment]
后续考虑加入鉴权绕过功能。

**Comment by weujieytt** [comment]
> 后续考虑加入鉴权绕过功能。

遇到/api-docs?group=openapi这种情况就扫不出来了

**Comment by yuligesec** [comment]
这是哪个框架的？有没有外网url。

**Comment by weujieytt** [comment]
> 这是哪个框架的？有没有外网url。

这也是springboot的，只是平常项目上遇到了不少，不加group=xxx访问不到，https://blog.csdn.net/weixin_42425967/article/details/113044573

**Comment by yuligesec** [comment]
fofa找的Knife4j是没有问题的，你用最新版再试试吧，和不加group=xxx没有关系，默认获取到API文档地址就是带group的。

**Comment by F6JO** [comment]
+1 有的目标不加group请求不到目录比如访问"/v3/api-docs?group=系统模块"是正常，访问/v3/api-docs就是404了

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.1 可以解决该问题。
