### ISSUE TITLE
爬目录问题

### ISSUE THREAD

**Issue by hackd0g** [API-Security/APIKit#15]
能否修改下爬到api或者actuator的时候，在当前actuator下面跑env等的目录
![image](https://user-images.githubusercontent.com/33395732/192921641-02141983-c395-4c1e-b35c-cce17d7440fb.png)

**Comment by yuligesec** [comment]
APIKit v1.4解决了这个bug。

https://github.com/API-Security/APIKit/releases/tag/v1.4
