### ISSUE TITLE
建议添加可添加多个headers的功能，以及可覆盖headers功能

### ISSUE THREAD

**Issue by no001ce** [API-Security/APIKit#22]
工具非常好用，结合日常工作想提些建议：

1、建议添加**可添加多个headers**的功能；
目前工具可以自定义扫描且可以设置headers，但是好像并不可以设置多个headers，我试过这样设置：header1: abc; headers2: cba，但并没用起作用；

2、建议可设置自定义的headers是否覆盖，或者可选择不自动构造 api 文档中的 headers；
此提议来自于扫描到某个 swagger-ui.html 的情况，其里面的文档指示已经设置有了 Authorization，工具在自动发送请求的时候会提取 api 文档所需的参数，也就是自动会带上 Authorization: test 去请求，此时若再自定义正确的 Authorization，请求里就会出现两个 Authorization 从而导致请求错误。

**Comment by F1echazo** [comment]
铜球

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.1 已解决该问题。
