### ISSUE TITLE
建议给DELETE加个开关

### ISSUE THREAD

**Issue by qaz7791869** [API-Security/APIKit#23]
如果被动测试的时候，真的未授权DELETE了，有点危险，建议默认关闭DELETE，可选择手动打开

**Comment by lif3reb00t** [comment]
作者考虑到这个了，问题不大
<img width="692" alt="image" src="https://user-images.githubusercontent.com/37888957/229762640-9b88c09c-1ac4-492d-b724-fd1fc6a48100.png">

**Comment by yuligesec** [comment]
避免出现生产事故所以默认情况下自动请求是关闭的，只探测API文档。
