### ISSUE TITLE
APIKit插件那没有任何数据

### ISSUE THREAD

**Issue by Top-Fish** [API-Security/APIKit#29]
1. 环境情况如下
- burpsuit v1.7.35
- firefox浏览器配置了127.0.0.1：8080代理，burpsuite代理处有流量，网站可以正常访问
- APIKit没有数据
2. 说明：
我访问的API信息如下：
https://172.24.23.139/apisec/v1/thlog/data/thead
https://172.24.23.139/apisec/v1/detect/desensitize/template?offset=0&limit=10
网站并提供没有任何的文档。

3. 我想咨询的是：
- 被动扫描我理解，可以不依赖文档，咱们这个插件依赖文档吗(被动扫描)
- 如果没有文档，只根据流量能扫描出内容吗？

**Comment by she1bye** [comment]
我也有类似的问题，比如这个网站`https://transaction.mzapi.mezzofy.com/`无论是被动扫描，还是自己点击`Do Target API Scan`，APIKit都没有这个网站的结果

![image](https://github.com/API-Security/APIKit/assets/41466845/07c5504b-051e-432f-87d0-d5d759cbfc52)

![image](https://github.com/API-Security/APIKit/assets/41466845/041f1311-b0d5-41dc-a6a8-c1f790b2a9ab)

红框中的网站也不是被动扫描的结果，是自己点击`Do Auto API Scan`的结果

![image](https://github.com/API-Security/APIKit/assets/41466845/37f1cf1a-1173-40bf-b6de-7ed4b9047b9b)

环境是burp2023.6，运行插件的java版本是11.0.18

运行时有报这样的错误，这是java版本有关吗？

`com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 7 path $`

![image](https://github.com/API-Security/APIKit/assets/41466845/23683933-1ef9-4974-8df1-a8e822512cca)

![image](https://github.com/API-Security/APIKit/assets/41466845/cb3518e0-de79-41f8-9180-0a2169f60807)

**Comment by yuligesec** [comment]
> 1. 环境情况如下
> 
> * burpsuit v1.7.35
> * firefox浏览器配置了127.0.0.1：8080代理，burpsuite代理处有流量，网站可以正常访问
> * APIKit没有数据
> 
> 2. 说明：
>    我访问的API信息如下：
>    https://172.24.23.139/apisec/v1/thlog/data/thead
>    https://172.24.23.139/apisec/v1/detect/desensitize/template?offset=0&limit=10
>    网站并提供没有任何的文档。
> 3. 我想咨询的是：
> 
> * 被动扫描我理解，可以不依赖文档，咱们这个插件依赖文档吗(被动扫描)
> * 如果没有文档，只根据流量能扫描出内容吗？

APIKit是基于API文档的，没有API文档不能扫描。

**Comment by yuligesec** [comment]
> 我也有类似的问题，比如这个网站`https://transaction.mzapi.mezzofy.com/`无论是被动扫描，还是自己点击`Do Target API Scan`，APIKit都没有这个网站的结果
> 
> ![image](https://user-images.githubusercontent.com/41466845/261823246-07c5504b-051e-432f-87d0-d5d759cbfc52.png)
> 
> ![image](https://user-images.githubusercontent.com/41466845/261823333-041f1311-b0d5-41dc-a6a8-c1f790b2a9ab.png)
> 
> 红框中的网站也不是被动扫描的结果，是自己点击`Do Auto API Scan`的结果
> 
> ![image](https://user-images.githubusercontent.com/41466845/261823387-37f1cf1a-1173-40bf-b6de-7ed4b9047b9b.png)
> 
> 环境是burp2023.6，运行插件的java版本是11.0.18
> 
> 运行时有报这样的错误，这是java版本有关吗？
> 
> `com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 7 path $`
> 
> ![image](https://user-images.githubusercontent.com/41466845/261823563-23683933-1ef9-4974-8df1-a8e822512cca.png)
> 
> ![image](https://user-images.githubusercontent.com/41466845/261823622-cb3518e0-de79-41f8-9180-0a2169f60807.png)

APIKit是基于API文档的，没有现成API文档不能扫描。你贴的这个网站（https://transaction.mzapi.mezzofy.com/）就没有API文档。
