### ISSUE TITLE
1.5仍然存在bug

### ISSUE THREAD

**Issue by K0uaz** [API-Security/APIKit#30]
版本：1.5
burpsuite:2023.5

请求仍然自动带上上级目录，导致对actuator端点遍历进了两层根目录中
![image](https://github.com/API-Security/APIKit/assets/32475005/786feeaa-636e-4e91-ae73-f6633d033d25)

![image](https://github.com/API-Security/APIKit/assets/32475005/1fbab418-44b4-48c1-b67d-21271c1851d5)

**Comment by yuligesec** [comment]
特殊情况，请自行解决：右键 -> Do Target API SCAN -> 手动指定actuator地址 并将baseurl指向根目录。

**Comment by K0uaz** [comment]
> 特殊情况，请自行解决：右键 -> Do Target API SCAN -> 手动指定actuator地址 并将baseurl指向根目录。

通过该种方式，确实可行😘
