### ISSUE TITLE
大佬你好，请问这个插件是只适配老版本的Burp吗？就红色图标那个

### ISSUE THREAD

**Issue by sansaniii2023** [API-Security/APIKit#31]
蓝色图标的burp安装的时候又提示成功安装然后error里面也有输出，我将error里的输出复制粘贴去问gpt，gpt回复：

该错误是由于rubyobj.ExtensionUI没有定义或继承ComponentListener接口的componentShown和componentHidden方法导致的。可能是因为插件的代码不兼容您正在使用的Burp版本。
尝试使用兼容您当前Burp版本的另一个版本的插件，或者更新Burp到最新版本，并尝试重新安装插件。如果问题仍然存在，请查看插件文档或联系插件作者进行更多帮助。

应该就是不适配新版本导致无法正常使用该插件，后面我会尝试安装旧版本的burp，希望大佬也能抽空看一下是否是版本不适配的原因，最后感谢大佬制作的插件

**Comment by yuligesec** [comment]
我这边用v202310.3没问题
