### ISSUE TITLE
Do Target Api

### ISSUE THREAD

**Issue by Gs52jrfnxnPXBGAW** [API-Security/APIKit#32]

**Comment by Gs52jrfnxnPXBGAW** [comment]
比如 https://xxxxx/api/v2/api-docs?group= ， 这个group=需要带上 但是我输入到里面 最终在展现结果中没有带上group=导致无法扫描出结果

**Comment by yuligesec** [comment]
好的，后面新版本会修复这个问题。

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.1 解决该问题。
