### ISSUE TITLE
加载插件时导致 burp 卡死

### ISSUE THREAD

**Issue by ll160803** [API-Security/APIKit#34]
加载插件时导致 burp 卡死
<img width="922" alt="image" src="https://github.com/API-Security/APIKit/assets/88411423/e952eda4-e2eb-46ff-8fab-852fdb202930">
<img width="751" alt="image" src="https://github.com/API-Security/APIKit/assets/88411423/cbb800cd-530b-410e-8320-e4815239a423">

**Comment by Superhero-zero** [comment]
+1  在使用2022.6.版本的BP加载该插件会导致整个BP卡死。
![image](https://github.com/API-Security/APIKit/assets/66772820/75994218-86c9-48b0-9615-5502be83862d)

**Comment by DatangST** [comment]
我也出现了这个问题，
![image](https://github.com/API-Security/APIKit/assets/52750566/3a2305e6-a093-4096-8212-4c99ebbe9b99)
2023.9版本

**Comment by yuligesec** [comment]
我这边使用的2023.10.3没出现这个问题，可否描述清楚环境呢

**Comment by yuligesec** [comment]
发现共同点了，你们是不是都是用的中文版插件...

**Comment by Superhero-zero** [comment]
我是用的中文版BP。

**Comment by yuligesec** [comment]
不知道和JDK有没有关系，刚刚用低版本jdk重新编译了一遍可以试试：https://github.com/API-Security/APIKit/releases/tag/v1.5.2

**Comment by Superhero-zero** [comment]
试了一下1.5.2版本 还是一样问题 师傅没有中文版BP吗 没有的话我发个中文版链接 师傅下载下来试试看 https://blog.csdn.net/m0_60571842/article/details/132140779

**Comment by ll160803** [comment]
已解决，和中文版应该没有关系，直接全部卸载，卸干净，然后重装 burp，就可以加载插件了

**Comment by ll160803** [comment]
> 已解决，和中文版应该没有关系，直接全部卸载，卸干净，然后重装 burp，就可以加载插件了

但是二次加载插件时依旧卡爆了，不管什么版本的 burp 都一样（中文版是在启动命令加了个 CN 的 jar 包）

**Comment by yuligesec** [comment]
你把中文版那个jar包去掉试试呢

**Comment by ll160803** [comment]
> 你把中文版那个jar包去掉试试呢

兄弟们，中文版害人呐 我把那个命令去掉 启动参数中不带BurpSuiteChs.jar就好了，随便加载 不卡不慢，作者大大牛逼

**Comment by Superhero-zero** [comment]
> > 你把中文版那个jar包去掉试试呢
> 
> 兄弟们，中文版害人呐 我把那个命令去掉 启动参数中不带BurpSuiteChs.jar就好了，随便加载 不卡不慢，作者大大牛逼

啥意思，去掉命令就不是中文版了吗

**Comment by yuligesec** [comment]
这个就是一个汉化包，不使用那个jar包就是英文版了。
