### ISSUE TITLE
base path url没有生效

### ISSUE THREAD

**Issue by ryanInf** [API-Security/APIKit#36]
你好！
burpsuite 2023.6.2
apikit 1.5.2

手动扫描时，api doc中的basePath值依然被强行带入，导致url不正确
![image](https://github.com/API-Security/APIKit/assets/19621374/db951ac7-b85c-4de6-89c5-4f303a2c7df2)

红框 这块多出来了
![image](https://github.com/API-Security/APIKit/assets/19621374/87b86554-6b0c-491e-8a0d-69f3d88edf73)

经过观察发现是从响应体中取了basePath的值，这个值不一定准确的，而手动传入的base path url没有生效
![image](https://github.com/API-Security/APIKit/assets/19621374/8327c30d-a734-4569-9083-fe5911c10b3d)

**Comment by yuligesec** [comment]
你在输入base Path URL的时候不加   /platform/ 不就行了。。。

**Comment by ryanInf** [comment]
> 你在输入base Path URL的时候不加 /platform/ 不就行了。。。

即便不加/platform/，拼接出来的url不一样也是错的么，变成/xxx//platform/v2/api-docs/xxxapi，而正确的是/xxx/platform/xxxapi

**Comment by yuligesec** [comment]
明白了，我感觉是这个API Doc本身就写错了，这种情况你可以把API Doc保存下来到本地，然后把basepath字段的内容改成"/"，然后启动一个本地http服务，Do Target API Scan的时候指定本地的http服务作为API Doc就行了。
