### ISSUE TITLE
当 openapi.json server 地址为空时，出现错误

### ISSUE THREAD

**Issue by hi-unc1e** [API-Security/APIKit#38]
# 问题说明
我的操作步骤：

- ![image](https://github.com/API-Security/APIKit/assets/67778054/4d3669eb-b408-4ab6-aedc-e1ba796fbeee)

出现的问题：

- ![image](https://github.com/API-Security/APIKit/assets/67778054/670ba77c-b027-4e5b-b70d-c2a31a50235b)

# 排查过程
排查出来，直接原因应该是：在遇到 `server` 地址为空时，没有判空，点此查看[涉事代码](https://github.com/API-Security/APIKit/blob/main/src/main/java/burp/application/apitypes/swagger/SwaggerObject.java#L113)

https://github.com/API-Security/APIKit/blob/main/src/main/java/burp/application/apitypes/swagger/SwaggerObject.java#L113

![image](https://github.com/API-Security/APIKit/assets/67778054/92e368f1-076b-4b94-b29d-be8fee5a881c)

# 参考
- 涉事openapi.json，https://[vampi.zeabur.app/openapi.json](https://vampi.zeabur.app/openapi.json)

**Comment by yuligesec** [comment]
好的 感谢提醒 已修复这个bug。https://github.com/API-Security/APIKit/releases/tag/v1.5.3
