### ISSUE TITLE
bp加载卡死，资源占用高

### ISSUE THREAD

**Issue by STARS7yao** [API-Security/APIKit#40]
burp加载jar包后无法正常使用，没有响应，cpu使用率高，强制退出重新打开bp，插件也不见了。

解决方式：设定burp扩展的时候指定标准输出文件和标准错误文件就正常了，不知道什么原因导致。
![image](https://github.com/API-Security/APIKit/assets/76717012/079e7c11-19e1-4950-93bd-e4263af79fc1)

**Comment by yuligesec** [comment]
这个可以看之前的issue是中文汉化包的问题。不用中文版就不会这样了

**Comment by tzf1003** [comment]
@yuligesec 
![image](https://github.com/API-Security/APIKit/assets/46259700/caea6fd4-4801-48ca-ac47-225389d9db8b)
我发现，是因为一直打印输出"=============="导致的卡死
