### ISSUE TITLE
加载一直报错

### ISSUE THREAD

**Issue by danran12** [API-Security/APIKit#43]
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<html>
<head><title>503 service temporarily unavailable</title></head>
<body>
<center><h1>503 service temporarily unavailable</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by yuligesec** [comment]
插件里没有用fastjson，目测和其他插件冲突了

**Comment by danran12** [comment]
是的，好像跟那个log4j的叼工具冲突了，关了就好了
