### ISSUE TITLE
漏报问题

### ISSUE THREAD

**Issue by kirs112** [API-Security/APIKit#44]
![image](https://github.com/API-Security/APIKit/assets/70934267/69567223-444b-4e26-bd69-0222e2cd70bf)

![image](https://github.com/API-Security/APIKit/assets/70934267/e5688cc5-7794-4c94-9f3b-226c00cf2ae0)

**Comment by kirs112** [comment]
做了一点改动 可以正常扫描出来

![image](https://github.com/API-Security/APIKit/assets/70934267/900b3218-51f0-43e3-a776-1449eb7aebba)

**Comment by yuligesec** [comment]
师傅 我看你加的代码是状态码404？ 不是400吗

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.4 最新版解决该问题，可以测一下。
