### ISSUE TITLE
被动扫描添加send with header

### ISSUE THREAD

**Issue by Deep0** [API-Security/APIKit#45]
大部分站点的鉴权参数在header头中，希望可以在被动扫描的时候带着原数据包中的全部请求头去请求。

**Comment by yuligesec** [comment]
好的，之前有这个功能但是莫名其妙失效了。

**Comment by Deep0** [comment]
那可能是哪里有bug吧，用的版本一直都是缺失带原请求头的请求数据包

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.4 最新版解决该问题。 可以测一下。
