### ISSUE TITLE
路径 显示问题

### ISSUE THREAD

**Issue by yuag** [API-Security/APIKit#47]
<img width="1375" alt="image" src="https://github.com/API-Security/APIKit/assets/34123873/a5abb66c-5271-4b1b-9561-62f91b3d7c38">

扫描出来的路径是      www.xxxx.com/emergency/xxxx

下面显示路径是这个
www.xxxx.com//caches

正确路径不应该是

www.xxxx.com/emergency/caches

**Comment by yuligesec** [comment]
右键 手动指定Base Path扫描

**Comment by yuag** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
