### ISSUE TITLE
主动扫描和被动扫描均无数据且报错

### ISSUE THREAD

**Issue by fantasyfanfan** [API-Security/APIKit#53]
主动扫描和被动扫描均无数据显示
![image](https://github.com/API-Security/APIKit/assets/20511789/f96eee65-4491-4642-a76a-a73c95ee5d31)
插件报错
![image](https://github.com/API-Security/APIKit/assets/20511789/fc2fb26b-5825-4fd8-a9ff-879314ff094f)
![image](https://github.com/API-Security/APIKit/assets/20511789/5b2dfb62-d898-43ec-8d9c-76037ef56a9a)

**Comment by yuligesec** [comment]
能描述清楚下复现步骤么

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.4 请用最新版再试试，gson那个报错应该不影响。

**Comment by YK1ngH** [comment]
你好，我用的是1.5.4的最新版，发现还是有同样的问题，用burp开了拦截之后，在apikit界面没有任何显示
![图片](https://github.com/user-attachments/assets/44418494-6ca1-44f3-87a7-e964fe274ece)
![图片](https://github.com/user-attachments/assets/4c71b313-25fd-48d1-87ad-13c1b4cd1f29)
