### ISSUE TITLE
能否更新下源码

### ISSUE THREAD

**Issue by k-vulner** [API-Security/APIKit#54]
源码还是1.0版本，能否和release版本相对应更新下源码，谢谢。在使用过程中发现被动扫描没有触发，使用的是APIsandbox里的owasp的实验靶场。是否对burp的版本和jdk版本有要求？

**Comment by yuligesec** [comment]
源码反编译也能看到，刚测了一下owasp那个靶场swagger应该没啥问题，后面我再发布一个版本吧

**Comment by yuligesec** [comment]
https://github.com/API-Security/APIKit/releases/tag/v1.5.4 请用最新版再试试
